# Generated by Django 3.1 on 2020-09-04 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200902_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.taskgroup'),
        ),
    ]
